# docker-compose.yaml
services:
  orders-service:
    image: orders-service
    build:
      context: .
      dockerfile: Dockerfile
      target: orders-service
    ports:
      - '50051/tcp'

  gateway-service:
    image: gateway-service
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway-service
      args:
        ORDER_SERVICE_ADDRESS: orders-service:50051
    ports:
      - '8080:8080'
